server:
  port: 9201

service-url:
  personal-info-service: http://localhost:8101
  appointment-service: http://localhost:8201
spring:
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.205.56:8848
        username: nacos
        password: microservice
    sentinel:
      transport:
        dashboard: 8.130.167.87:8090
        clientIp: 8.130.167.87
        port: 8719
    gateway:
      routes:
        - id: patient-info
          uri: ${service-url.personal-info-service}
          predicates:
            - Path=/patient-info/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/patient

        - id: appointment-service
          uri: ${service-url.appointment-service}
          predicates:
            - Path=/appointment/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/appointment

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9101/rsa/publicKey' #配置RSA的公钥访问地址
