server:
  port: 8201

spring:
  application:
    name: appointment-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.205.56:8848
        username: nacos
        password: microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-pe33ibr74001zlgo.rwlb.rds.aliyuncs.com:3306/order?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Tongji123

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


