server:
  port: 8201

spring:
  application:
    name: appointment-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.205.56:8848
        username: nacos
        password: microservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-pe33ibr74001zlgo.rwlb.rds.aliyuncs.com:3306/order?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Tongji123
  redis:
    host: 47.115.205.56
    port: 6379
    password: microservice
  rabbitmq:
    host: 47.115.205.56
    port: 5672
    username: rabbitmq
    password: microservice
    virtualHost: /

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


